CREATE TABLE "websurfing_account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "websurfing_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "websurfing_cell" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"rowIndex" integer NOT NULL,
	"colIndex" integer NOT NULL,
	"content" text,
	"createdAt" timestamp with time zone DEFAULT now(),
	"updatedAt" timestamp with time zone DEFAULT now(),
	CONSTRAINT "cell_unique_position" UNIQUE("rowIndex","colIndex")
);
--> statement-breakpoint
CREATE TABLE "websurfing_event_queue" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"eventType" varchar(100) NOT NULL,
	"payload" jsonb NOT NULL,
	"status" varchar(20) DEFAULT 'pending',
	"createdAt" timestamp with time zone DEFAULT now(),
	"processedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "websurfing_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "websurfing_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "websurfing_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "websurfing_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp with time zone,
	"image" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "websurfing_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "websurfing_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "websurfing_account" ADD CONSTRAINT "websurfing_account_userId_websurfing_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."websurfing_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "websurfing_post" ADD CONSTRAINT "websurfing_post_createdById_websurfing_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."websurfing_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "websurfing_session" ADD CONSTRAINT "websurfing_session_userId_websurfing_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."websurfing_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "websurfing_account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "cell_position_idx" ON "websurfing_cell" USING btree ("rowIndex","colIndex");--> statement-breakpoint
CREATE INDEX "event_queue_status_idx" ON "websurfing_event_queue" USING btree ("status");--> statement-breakpoint
CREATE INDEX "event_queue_created_idx" ON "websurfing_event_queue" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "websurfing_post" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "name_idx" ON "websurfing_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "t_user_id_idx" ON "websurfing_session" USING btree ("userId");